version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5690:8080"
    volumes:
      - ./server:/service
    secrets:
      - BOT_TOKEN
      - RTSP_URL

secrets:
  BOT_TOKEN:
    file: ./secrets/BOT_TOKEN
  RTSP_URL:
    file: ./secrets/RTSP_URL