name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile.build
          push: true
          tags: ghcr.io/taavettik/monitor-bot:dev

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: echo $KUBERNETES_CONFIG >/tmp/kubeconfig
        env:
          KUBERNETES_CONFIG: ${{ secrets.KUBERNETES_CONFIG }}
      - run: head -3 /tmp/kubeconfig
      - run: terraform init
      - run: terraform apply
